openapi: 3.0.0
info:
  title: Messy API
  version: 1.0.0

paths:
  /stuff:
    get:
      summary: Get stuff
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: string
    post:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: boolean
                  error:
                    type: string

  /stuff/{id}:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
        '404':
          description: Not found
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Updated
        '500':
          description: Server error

components:
  schemas:
    SomeObject:
      type: object
      properties:
        key:
          type: string